# app/xray_config.py
# Goal: build & validate Xray-core JSON config from DB; atomic write (APPENDIX A.9).
# Author: OpenCode
from __future__ import annotations

import json
import os
import secrets

from .config import settings
from .models import User

REQUIRED_TAGS = {"vless-ws", "vmess-ws", "trojan-ws", "reality-in"}


def generate_reality_keys() -> dict:
    """Random placeholder keys; real x25519 keys are generated by `xray x25519`
    at install time and stored in settings (reality_priv/pub/sid)."""
    return {
        "privateKey": secrets.token_hex(32),
        "publicKey": secrets.token_hex(32),
        "shortId": secrets.token_hex(4),
    }


def _clients_vless(users: list[User]) -> list[dict]:
    return [{"id": u.uuid, "email": u.name} for u in users]


def _clients_vmess(users: list[User]) -> list[dict]:
    return [{"id": u.uuid, "email": u.name, "alterId": 0} for u in users]


def _clients_trojan(users: list[User]) -> list[dict]:
    return [{"password": u.trojan_pass, "email": u.name} for u in users]


def _clients_ss(users: list[User]) -> list[dict]:
    return [{"password": u.ss_pass, "email": u.name} for u in users]


def build_config(users: list[User], s: settings.__class__, paths: dict, reality_keys: dict | None = None) -> dict:
    """Build the full Xray JSON config. Users must all be enabled."""
    users = [u for u in users if u.enabled]
    rk = reality_keys or generate_reality_keys()
    panel_port = s.port
    inbounds: list[dict] = [
        {
            "tag": "api-in", "port": 10085, "listen": "127.0.0.1",
            "protocol": "dokodemo-door", "settings": {"address": "127.0.0.1"},
        },
        {
            "tag": "vless-ws", "port": panel_port, "protocol": "vless",
            "settings": {"clients": _clients_vless(users), "decryption": "none"},
            "streamSettings": {"network": "ws", "wsSettings": {"path": paths["vless"]}},
        },
        {
            "tag": "vmess-ws", "port": panel_port, "protocol": "vmess",
            "settings": {"clients": _clients_vmess(users)},
            "streamSettings": {"network": "ws", "wsSettings": {"path": paths["vmess"]}},
        },
        {
            "tag": "trojan-ws", "port": panel_port, "protocol": "trojan",
            "settings": {"clients": _clients_trojan(users)},
            "streamSettings": {"network": "ws", "wsSettings": {"path": paths["trojan"]}},
        },
    ]
    if s.ss_port and s.ss_port > 0:
        inbounds.append({
            "tag": "ss-in", "port": s.ss_port, "protocol": "shadowsocks",
            "settings": {"method": "aes-256-gcm", "clients": _clients_ss(users), "network": "tcp,udp"},
        })
    inbounds.append({
        "tag": "reality-in", "port": s.reality_port, "protocol": "vless",
        "settings": {"clients": [{"id": u.uuid, "email": u.name, "flow": "xtls-rprx-vision"} for u in users],
                     "decryption": "none"},
        "streamSettings": {
            "network": "tcp", "security": "reality",
            "realitySettings": {
                "show": False, "dest": f"{s.reality_sni}:443", "xver": 0,
                "serverNames": [s.reality_sni],
                "privateKey": rk["privateKey"], "shortIds": [rk["shortId"]],
            },
        },
    })
    return {
        "log": {"loglevel": "warning", "access": "none"},
        "api": {"tag": "api", "services": ["HandlerService", "StatsService"]},
        "stats": {},
        "policy": {"levels": {"0": {"statsUserUplink": True, "statsUserDownlink": True}}},
        "inbounds": inbounds,
        "outbounds": [
            {"tag": "direct", "protocol": "freedom"},
            {"tag": "blocked", "protocol": "blackhole"},
        ],
        "routing": {"rules": [{"type": "field", "inboundTag": ["api-in"], "outboundTag": "api"}]},
    }


def validate_config(cfg: dict) -> tuple[bool, str]:
    """Check required tags, non-empty clients, numeric ports."""
    try:
        tags = {i.get("tag") for i in cfg["inbounds"]}
    except (KeyError, TypeError):
        return False, "inbounds missing"
    for tag in REQUIRED_TAGS:
        if tag not in tags:
            return False, f"missing inbound {tag}"
    for i in cfg["inbounds"]:
        if not isinstance(i.get("port"), int):
            return False, f"port of {i.get('tag')} not numeric"
        clients = (i.get("settings") or {}).get("clients")
        if clients is not None and not isinstance(clients, list):
            return False, f"clients of {i.get('tag')} invalid"
    return True, ""


def write_config(cfg: dict, path: str) -> None:
    """Atomic write: tmp file + rename so a crash never leaves a partial config."""
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(cfg, f, ensure_ascii=False, indent=2)
    os.replace(tmp, path)


def rebuild_and_reload(session=None, supervisor=None) -> bool:
    """Build → validate → write → graceful reload. Returns True on success."""
    from .config import settings as st

    users = []
    if session is not None:
        from sqlmodel import select

        from .models import User

        users = session.exec(select(User)).all()
    paths = {"vless": "/vless", "vmess": "/vmess", "trojan": "/trojan"}
    try:
        with open(os.path.join(st.data_dir, "paths.json"), encoding="utf-8") as f:
            paths = json.load(f)
    except (OSError, json.JSONDecodeError):
        pass
    cfg = build_config(users, st, paths)
    ok, reason = validate_config(cfg)
    if not ok:
        return False
    write_config(cfg, os.path.join(st.data_dir, "xray-config.json"))
    if supervisor is not None:
        supervisor.reload_xray()
    return True
